font = "Segoe UI Variable Display"
dark_mode = true

method = "Karachi"
location_name = "Rajshahi"

critical_at = 15
ishraq = [15, 5]

[asr]
mode = "DhuhrEndsAtAsrThaaniButAsrStartsAtAsrAwwal"

[coordinates]
latitude = 24.383144
longitude = 88.583183

[user_adjustments]
fajr = 0
sunrise = 0
dhuhr = 0
asr = 0
maghrib = 0
isha = 0
